HPSCTerrSys/TSMP

.gitignore, bldsva/build_tsmp.ksh
I propose a `.gitignore` for the main directory, since during build and setup, many directories are generated in this directory that should (in my opinion) never be part of the git repository of TSMP.
=> .gitignore: Ignore /bin/, /run/ and component software dirs

bldsva/intf_oas3/parflow3_7/arch/JURECA/build_interface_parflow3_7_JURECA.ksh, bldsva/intf_oas3/parflow3_7/arch/JUWELS/build_interface_parflow3_7_JUWELS.ksh
The build-interface is using hard-coded DPARFLOW_AMPS_LAYER=oas3,
which is not working without OASIS, as needed in standalone mode.
Adding a if-clause with fall-back of DPARFLOW_AMPS_LAYER=mpi1 in
case of OASIS is not compiled to fix this.
This fix is applied and tested for JUWELS and JURECA only.
=> BUGFIX is64 - building ParFlow standalone

bldsva/intf_DA/pdaf1_1/model/wrapper_tsmp.c
#114 
Unused variables removed - needs to be tested with FallSchoolCase before merge.
=> wrapper_tsmp, initialize_tsmp: remove unused variables

bldsva/intf_oas3/parflow3_0/arch/AGROCLUSTER/build_interface_parflow3_0_AGROCLUSTER.ksh, bldsva/intf_oas3/parflow3_0/arch/CCA2/build_interface_parflow3_0_CCA2.ksh, bldsva/intf_oas3/parflow3_0/arch/GENERIC_X86/build_interface_parflow3_0_GENERIC_X86.ksh, bldsva/intf_oas3/parflow3_0/arch/JURECA/build_interface_parflow3_0_JURECA.ksh, bldsva/intf_oas3/parflow3_0/arch/JUWELS/build_interface_parflow3_0_JUWELS.ksh
=> intf_oas/parflow3_0: change old pathnames containing `parflow/`

.github/workflows/main.yml, doc/conf.py, doc/content/best_practices.md, doc/content/branches.md, doc/content/build_environment_variables.md, doc/content/build_examples.md, doc/content/build_examples_tsmp.md, doc/content/build_examples_tsmppdaf.md, doc/content/contributing/documentation.md, doc/content/debugging.md, doc/content/development.md, doc/content/gettingstarted.md, doc/content/input_clm.md, doc/content/input_cmd.md, doc/content/input_cos.md, doc/content/input_enkfpf.md, doc/content/input_oas.md, doc/content/input_obs.md, doc/content/input_pfl.md, doc/content/installation.md, doc/content/intf_da.md, doc/content/introduction.md, doc/content/jsc.md, doc/content/misc.md, doc/content/pdaf.md, doc/content/remotes.md, doc/content/running.md, doc/content/setup_examples.md, doc/content/structure.md, doc/index.rst
Migrate existing TSMP documentation (as it is) from JSC GitLab [TSMP_manual](https://gitlab.jsc.fz-juelich.de/sdlts/tsmp_manual) to TSMP master.  
This PR is intended to consolidate all existing documentation into the official TSMP GitHub repo, so that no other repos are needed.
=> Migrate exisiting documentation from JSC GitLab

bldsva/build_tsmp.ksh, bldsva/intf_oas3/clm3_5/tsmp/Biogeophysics1Mod.F90, bldsva/intf_oas3/common_build_interface.ksh
- set `maxpft=4` as new default in `bldsva/intf_oas3/common_build_interface.ksh`
- rewrite workaround in `bldsva/intf_oas3/common_build_interface.ksh` correcting `forc_hgt` according to pft types present in CLM35 grid cell. This is now working for `maxpft!=1` as well.
=> Enable maxpft>1

bldsva/intf_oas3/cosmo4_21/oas3/receive_fld_2clm.F90, bldsva/intf_oas3/cosmo5_1/oas3/receive_fld_2clm.F90
Currently, dummy values are used for COSMO in coupled mode until the first coupling time step. The dummy values are originally a bandaid for the halo-regions and contain typical values for a night in summer at mid-latitudes. The usage of the dummy values leads to diverging results between a restarted simulation of a coupled simulation with COSMO-CLM(-ParFlow) and an initial simulation. This is unintended, and due to the fix the dummy values will only be written at the initial step (`istep==0`).
The effect of the fix is biggest for restarted simulation with a large coupling time step between COSMO-CLM as well as simulation at noon and/or surface temperature (`tsf >>/<< 287.589 K`)
Caution: This code change will change the results of a restarted simulation. The restarted simulation will not …
=> Fix COSMO coupled mode dummy values usage for restart

bldsva/intf_oas3/parflow/arch/build_interface_parflow.ksh, bldsva/lib_install.sh
Hello all,
Here are a couple fix / usability improvements from my experience installing and running (successfully) TSMP on a Linux cluster. Only on the 'cordex' test case so far though.
Since we didn't have the many dependencies needed installed in some central management, I went the `lib_install.sh` route to install locally everything, which no current configuration (bldsva/machines/config_XXX.ksh) does if I'm not mistaken.
I also built TSMP on top of MPICH (v4.1.1) which was not as simple as I would've hoped, but overall went ok. 
I'll make a separate PR to introduce a mpich-based `lib_install.sh` (the rest of the build scripts with the `Gnu` compilers still works fine), and probably another PR to upstream the cluster's configuration ksh script.
=> Misc fixes

bldsva/intf_oas3/clm3_5/arch/build_interface_clm3_5.ksh
This small fix streamlines the clm3_5 compilation with non-standard environments.
=> Improve compiler detection in clm3_5 compilation

bldsva/setup_tsmp.ksh
Before: Copy `coup_oas.tcl` if it does not exist in `$rundir`
Now: Copy `coup_oas.tcl` if it does not exist in `$rundir` OR if there are multiple ensemble members!
=> `c_setup_pfl`: adapt condition for copying `coup_oas.tcl` to ensemble runs

bldsva/setups/common_setup.ksh, bldsva/setups/cordex/cordex.ksh, bldsva/setups/ideal1200600/ideal1200600.ksh, bldsva/setups/ideal24001200/ideal24001200.ksh, bldsva/setups/ideal300150/ideal300150.ksh, bldsva/setups/ideal600300/ideal600300.ksh, bldsva/setups/idealRTD/idealRTD.ksh, bldsva/setups/idiurnal-cycle/idiurnal-cycle.ksh, bldsva/setups/nrw/nrw.ksh
additionally: change existing setups, such that `static_files` variable is defined with `$rootdir` prefix.
=> common_setup.ksh: define location of static files in single variable

doc/conf.py, doc/content/faq/documentation.md
I replaced the `View page source` button in the top right corner of each documentation subpage by the `Edit on GitHub` button.
Further I added a section under `doc/content/faq/documentation.md` explaining how to use this button properly.
Please do checkout and test this button.
It may be that some branch protection rules need to be adjusted to ensure that outstanding people cannot push to the master without PR, if not already set.
As rendering the doc for PR from forks does lead to some permission error, please do check the rendered doc in my fork:
https://niklaswr.github.io/TSMP/content/faq/documentation.html
=> Add EditOnGitHub button

bldsva/setups/common_setup.ksh, bldsva/setups/ideal1200600/coup_oas.tcl, bldsva/setups/ideal24001200/coup_oas.tcl, bldsva/setups/ideal300150/coup_oas.tcl, bldsva/setups/ideal600300/coup_oas.tcl, bldsva/setups/idiurnal-cycle/idiurnal-cycle.ksh
I introduced some if checks to reduce the error print-outs in common_setup.ksh.
Additionally, there were bugs in the idealscal (not matching names) and the idiurnal-cycle (path-issues) setups.
=> More checks to reduce error print outs and fixes for idealscal and idiurnal-cycle

bldsva/setups/common_setup.ksh
In the past, remap-files were always provided with the name rmp_gcos_to_gclm_BILINEA.nc. Therefore, the setup added a "R" at the end. The files for ideal1200600, etc. already have the name rmp_gcos_to_gclm_BILINEAR.nc. A check was added to account for that.
=> Correct remap renaming for idealscal

bldsva/build_tsmp.ksh
Example: Before this PR, the command
`./build_tsmp.ksh -c clm5-pdaf -m JURECA -O Intel -B
bin/JURECA_clm5-pdaf-debug`
created the `bindir` inside `bldsva`, i.e.
```
$rootdir/bldsva/bin/JURECA_clm5-pdaf-debug
```
After this PR `bindir` is created in the
`$rootdir`. This is how the default-bindirs are placed:
```
$rootdir/bin/JURECA_clm5-pdaf-debug
```
Additionally, it is safer to use an absolute path in `finalizeSelection`.
=> build: `bindir` input (from flag `-B`) applied to rootdir

bldsva/intf_DA/pdaf/framework/finalize_pdaf.F90, bldsva/intf_DA/pdaf/framework/init_dim_obs_f_pdaf.F90, bldsva/intf_DA/pdaf/framework/init_dim_obs_l_pdaf.F90, bldsva/intf_DA/pdaf/framework/init_dim_obs_pdaf.F90, bldsva/intf_DA/pdaf/framework/localize_covar_pdaf.F90, bldsva/intf_DA/pdaf/framework/mod_assimilation.F90, bldsva/intf_DA/pdaf/framework/mod_tsmp.F90, bldsva/intf_DA/pdaf/model/parflow/enkf_parflow.c, bldsva/intf_DA/pdaf/model/parflow/enkf_parflow.h
- `xcoord_fortran_g`
- `ycoord_fortran_g`
- `zcoord_fortran_g`
Move assignment of the Fortran pointer `xcoord_fortran`,
`ycoord_fortran`, `zcoord_fortran` from the global observation
initialisation routines (`init_dim_obs_pdaf` and
`init_dim_obs_f_pdaf`) to the routines, where they are used:
- `localize_covar`: LEnKF covariance localization
- `init_dim_obs_l_pdaf`: LETKF/LESTKF setting local
observation vector of the local analysis domain
Change size of `xcoord`, `ycoord`, `zcoord` to `enkf_subvecsize`,
i.e. only the size of one (grid-sized) subvector of the entire state
vector. (`enkf_parflow.c`).
For usage of the coordinate arrays in `init_dim_obs_l_pdaf` and
`localize_covar_pdaf`, the indices for the coordinate array have to
use `modulo` to project the general state vector index onto …
=> Refactoring the use of `xcoord`, `ycoord`, `zcoord` and corresponding Fortran arrays

bldsva/intf_DA/pdaf/framework/finalize_pdaf.F90, bldsva/intf_DA/pdaf/framework/init_dim_obs_f_pdaf.F90, bldsva/intf_DA/pdaf/framework/init_dim_obs_pdaf.F90, bldsva/intf_DA/pdaf/framework/mod_assimilation.F90, bldsva/intf_DA/pdaf/framework/obs_op_f_pdaf.F90
`local_dims_obs` was before set at the end of the global observation
initalization routines. However, it is more fitting to set it in the
code-part, where the observation dimensions are set, not after the
code part, where observation arrays are filled.
Before `local_dims_obs` was only deallocated directly before
allocation.
`local_dim` is local clone of `local_dims_obs`. Therefore, `local_dim`
is removed and its role in setting the array `local_dis` is now filled
by `local_dims_obs`.
- clearer name `local_disp_obs`
- preventing code duplicity of setting `local_dis`
- simplified usage in observation operator routine
Disadvantage:
No immediate deallocation in local routine, should be ok as
`local_disp_obs` islength of number of PEs.
- use `dim_obs_p` where possible
- check that `dim_obs_p` …
=> Refactor use of  `local_dims_obs` array

bldsva/intf_DA/pdaf/framework/add_obs_error_pdaf.F90, bldsva/intf_DA/pdaf/framework/init_dim_obs_f_pdaf.F90, bldsva/intf_DA/pdaf/framework/init_dim_obs_pdaf.F90, bldsva/intf_DA/pdaf/framework/init_obscovar_pdaf.F90, bldsva/intf_DA/pdaf/framework/localize_covar_pdaf.F90, bldsva/intf_DA/pdaf/framework/mod_assimilation.F90
slightly longer compute time, but much clearer code
If no point observations are used, the usage of `obs_nc2pdaf` is
spurious.
=> TSMP-PDAF: Refactor setting and usage of `obs nc2pdaf`

bldsva/intf_DA/pdaf/framework/add_obs_error_pdaf.F90
Former `dim_obs_p` in `add_obs_error_pdaf` was actually the size of the full observation vector and is therefore better called `dim_obs`.
The suffix `_p` is used in TSMP-PDAF for PE-local variables.
=> PDAF: change `dim_obs_p` to `dim_obs` in `add_obs_error_pdaf` (LEnKF)

bldsva/intf_DA/pdaf/framework/localize_covar_pdaf.F90
This input variable to `localize_covar_pdaf` is the PE-local state dimension.
However, `dim_state` is a double-name with the global state dimension from module `mod_assimilation`.
=> PDAF: Rename `dim_state` to `dim_p` in `localize_covar_pdaf`

bldsva/intf_DA/pdaf/framework/add_obs_error_pdaf.F90, bldsva/intf_DA/pdaf/framework/init_dim_obs_f_pdaf.F90, bldsva/intf_DA/pdaf/framework/init_dim_obs_pdaf.F90, bldsva/intf_DA/pdaf/framework/init_obscovar_pdaf.F90, bldsva/intf_DA/pdaf/framework/localize_covar_pdaf.F90, bldsva/intf_DA/pdaf/framework/mod_assimilation.F90
Reason: `obs_pdaf2nc` takes as input a pdaf-ordered index (subdivision according to PEs) and outputs the nc-ordered index (order from the NetCDF observation file)
=> PDAF: rename `obs_nc2pdaf` to `obs_pdaf2nc`

bldsva/intf_DA/pdaf/framework/localize_covar_pdaf.F90, bldsva/intf_DA/pdaf/model/clm3_5/enkf_clm_mod.F90, bldsva/intf_DA/pdaf/model/clm5_0/enkf_clm_mod_5.F90, bldsva/intf_DA/pdaf/model/eclm/enkf_clm_mod_5.F90
- IMPORTANT: Changed from index-distance to lat/lon distance
- introduce PE-local index transformation arrays `state_pdaf2clm_c_p` (column) and `state_pdaf2clm_j_p` (layer)
- loop over global pdaf-ordered observations and PE-local pdaf-ordered state
- manage access to the arrays with index transformation arrays, e.g. `lon(mygridcell(state_pdaf2clm_c_p(i))))` transforms the PE-local pdaf-ordered state index `i`: (1) to the CLM column index, (2) to the CLM gridcell index and (3) to the gridcell's longitude.
=> PDAF: LEnKF for eCLM-PDAF

bldsva/intf_DA/pdaf/model/clm3_5/enkf_clm_mod.F90, bldsva/intf_DA/pdaf/model/clm5_0/enkf_clm_mod_5.F90, bldsva/intf_DA/pdaf/model/eclm/enkf_clm_mod_5.F90
Goal: Eliminate the following warning that appears in `Stages/2024`:
ld: warning: size of symbol `outdir' changed
from 1 in
`${CMAKE_INSTALL_PREFIX}/lib/libmodel.a(enkf_clm_mod_5.o)`
to 100 in
`${CMAKE_INSTALL_PREFIX}/lib/libmodel.a(wrapper_tsmp.o)`
=> PDAF: give character `outdir` length 100

bldsva/intf_DA/pdaf/framework/Makefile
`LINK_LIBS` contains the most general libraries and should therefore be moved to the end of the command.
=> PDAF: Move `LINK_LIBS` to end of command

bldsva/intf_DA/pdaf/framework/g2l_obs_pdaf.F90, bldsva/intf_DA/pdaf/framework/init_dim_obs_f_pdaf.F90, bldsva/intf_DA/pdaf/framework/init_dim_obs_pdaf.F90, bldsva/intf_DA/pdaf/framework/mod_assimilation.F90, bldsva/intf_DA/pdaf/framework/obs_op_f_pdaf.F90
Only used in local filters (except LEnKF).
- renaming `m_id_f` to `obs_nc2pdaf_deprecated` in order to incorporate it in a common naming scheme.
- filling `obs_nc2pdaf` in observation dimension initialization routines (`init_dim_obs_*.F90`)
- testing `obs_nc2pdaf_deprecated` against `obs_nc2pdaf` to ensure that the latter may actually replace the former.
TODO at later stage (especially with testcase for LETKF ready): remove  `obs_nc2pdaf_deprecated`.
=> PDAF: Introduce observation index transformation `obs_nc2pdaf`

bldsva/intf_DA/pdaf/framework/obs_op_pdaf.F90, bldsva/intf_DA/pdaf/model/clm5_0/enkf_clm_mod_5.F90, bldsva/intf_DA/pdaf/model/common/enkf.h, bldsva/intf_DA/pdaf/model/common/read_enkfpar.c, bldsva/intf_DA/pdaf/model/eclm/enkf_clm_mod_5.F90, doc/content/setup_tsmp/input_enkfpf.md
Added implementation of Schrön 2017 operator to obs_op_pdaf for use with eCLM / CLM5 (not parflow).  Enable with crns_flag = 2 in enkfpf.par file. Optional parameter crns_bd = value for custom bulk density instead of bd calculated by clm.
=> CRNS method 2
